# Numpy Lab exercises (02.06.22)

### A collections of matrix operations using the numpy library

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [42]:
nvec = np.zeros(10)
print("Null vector =", nvec)

Null vector = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
nvec[4] = 1
print(nvec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [47]:
print("Vector with values in range(10,50) : \n", np.arange(10,50))

Vector with values in range(10,50) : 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [48]:
print(np.reshape(np.arange(0,9),(3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [49]:
print("indices of nonzero elements are: ", np.nonzero(np.array([1,2,0,0,4,0]))[0])

indices of nonzero elements are:  [0 1 4]


#### 7. Create a 3x3 identity matrix (★☆☆)

In [54]:
print("I3x3 = \n",np.eye(3))

I3x3 = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [58]:
print("A 3x3x3 random matrix is \n \n", np.random.randint(-100,100,(3,3,3)))

A 3x3x3 random matrix is 
 
 [[[-40 -88 -36]
  [ 92  37  38]
  [ 84  49 -56]]

 [[-66  43 -88]
  [-97 -67 -93]
  [ -8 -37  -2]]

 [[ 43 -46  81]
  [ 41  12  75]
  [-15 -26  31]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [59]:
print("min =", np.random.randint(-100,100,(10,10)).min())
print("max =", np.random.randint(-100,100,(10,10)).max())

min = -98
max = 95


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [63]:
print("mean(rand_vec) =", np.mean(np.random.random((1,30))))

mean(rand_vec) = 0.39411836138717943


#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [11]:
print(np.diag([1,2,3,4],k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)

<i> The norm of a matrix is defined as </i> $\mathbf{norm}(X)=(X-\bar{X})/\sigma_X$

In [66]:
x=np.random.random((5,5)) 
print("norm(mat) = \n",(x-np.mean(x))/np.std(x))

norm(mat) = 
 [[ 0.15486796 -1.92416019  0.38737422 -0.64914662  0.73327989]
 [ 1.33066202 -0.85470388  0.91686993  1.10356418  0.96567571]
 [ 0.27398893  1.00362447 -1.54235033 -1.15012194  0.46869965]
 [-0.08638807 -0.34624789 -0.59076252  1.20438144  0.25606374]
 [-0.01824011 -0.08111274 -1.46353895 -1.70792365  1.61564475]]


#### 13. How to find common values between two arrays? (★☆☆)

In [13]:
a1=np.arange(0,10,2)
a2=np.array([1,2,5])

In [69]:
print("common values =", np.intersect1d(a1,a2))

common values = [2]


#### 14. Create a random vector of size 10 and sort it (★★☆)

In [70]:
print("Sorted vector =", np.sort(np.random.randint(-10,10,(1,10)))[0])

Sorted vector = [-10  -5  -4  -2  -1  -1   0   1   5   7]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [75]:
a   = np.random.randint(-22,22,(1,10)) # random vec
print("Original matrix ", a[0])
m   = np.max(a)                # max value 
idx = np.where(a==m)[1]        # index of max (this is a bug it assumes that it only appears once!)
#print(idx)
a[0][idx]=0
print("Substited matrix =", a[0])

Original matrix  [ 15  -6 -11 -15  -9   4  -6  17  -2   1]
[7]
Substited matrix = [ 15  -6 -11 -15  -9   4  -6   0  -2   1]


#### 16. Subtract the mean of each row of a matrix (★★☆)

In [17]:
rmat = np.random.randint(-100,100,size=(4,4)) # generate a random matrix
rmat_subt_mean = rmat-np.diag(np.mean(rmat,axis=1)) # subtract the means (axis=1 gives means of the rows)
print(rmat_subt_mean)

[[ 46.    19.    -1.   -13.  ]
 [-97.    30.75 -69.    16.  ]
 [ 85.    42.    -9.25  36.  ]
 [-37.   -28.   -54.    91.25]]


#### 17. How to get the n largest values of an array (★★★)

In [18]:
v = np.random.rand(1,10) # first do it for a vector 
v = v[0]
print(v)

[0.77123284 0.04357365 0.63647624 0.45620314 0.25824047 0.6568753
 0.90945232 0.15731388 0.87085329 0.42433403]


In [19]:
def get_n_largest_of_vec(vec,n):
    vec.sort()
    vrev = v[::-1]
    return vrev[0:n]

In [20]:
print(get_n_largest_of_vec(v,3))

[0.90945232 0.87085329 0.77123284]


In [21]:
print(rmat)

[[ 63  19  -1 -13]
 [-97  -9 -69  16]
 [ 85  42  42  36]
 [-37 -28 -54  82]]


In [22]:
def get_n_largest_of_mat(mat,n):
    if type(n) != int:
        return print("Error: n must be an integer")   
    elif n > mat.size:
        return print("Error: n must be less that the number of elements of the matrix")
    mf = mat.flatten() # change it to a vector
    mf.sort() # sort it from low to high
    mfrev = mf[::-1] # reverse the order 
    return mfrev[0:n] # slice the top n values and return as a vector

In [23]:
print(get_n_largest_of_mat(rmat,10))

[85 82 63 42 42 36 19 16 -1 -9]


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36)

<i> Here we use the where method </i>

In [24]:
rmat35 = np.random.randint(0,10,size=(5,3))

print(rmat35)

rmat35=np.where(rmat35 > 4, rmat35 **2, rmat35)

print(rmat35)



[[5 8 6]
 [7 8 9]
 [0 2 9]
 [8 5 5]
 [7 2 7]]
[[25 64 36]
 [49 64 81]
 [ 0  2 81]
 [64 25 25]
 [49  2 49]]
