# Numpy Lab exercises (02.06.22)

### A collection of matrix operations using the numpy library

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
nvec = np.zeros(10)
print("Null vector =", nvec)

Null vector = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
nvec[4] = 1
print(nvec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
print("Vector with values in range(10,50) : \n", np.arange(10,50))

Vector with values in range(10,50) : 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [5]:
print(np.reshape(np.arange(0,9),(3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
np.reshape(np.arange(0,9),(3,3))[:,0]

array([0, 3, 6])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [7]:
print("indices of nonzero elements are: ", np.nonzero(np.array([1,2,0,0,4,0]))[0])

indices of nonzero elements are:  [0 1 4]


#### 7. Create a 3x3 identity matrix (★☆☆)

In [8]:
print("I3x3 = \n",np.eye(3))

I3x3 = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [9]:
print("A 3x3x3 random matrix is \n \n", np.random.randint(-100,100,(3,3,3)))

A 3x3x3 random matrix is 
 
 [[[  8 -92 -50]
  [ 69  84  97]
  [-10 -66 -59]]

 [[ 44   6 -15]
  [ 76 -76 -70]
  [ 69 -74 -98]]

 [[ 78 -34  63]
  [ 15  35  49]
  [ 43  97 -70]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [10]:
print("min =", np.random.randint(-100,100,(10,10)).min())
print("max =", np.random.randint(-100,100,(10,10)).max())

min = -94
max = 99


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [11]:
print("mean(rand_vec) =", np.mean(np.random.random((1,30))))

mean(rand_vec) = 0.559429450288058


#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [12]:
print(np.diag([1,2,3,4],k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)

<i> The norm of a matrix is defined as </i> $\mathbf{norm}(X)=(X-\bar{X})/\sigma_X$

In [13]:
x=np.random.random((5,5)) 
print("norm(mat) = \n",(x-np.mean(x))/np.std(x))

norm(mat) = 
 [[-0.25746858  1.76296911 -0.95317139  0.03132503  0.94066608]
 [ 0.52410171 -1.218132   -1.49139527 -0.53765116 -1.10907929]
 [-1.52207457  1.45967879 -1.3740952   1.30491516  0.16562822]
 [ 0.50557037 -0.14745541  0.71497133 -0.89824721 -0.95393082]
 [ 1.20736903  1.14743412 -0.58808855  0.71711176  0.56904874]]


#### 13. How to find common values between two arrays? (★☆☆)

In [14]:
a1=np.arange(0,10,2)
a2=np.array([1,2,5])

In [15]:
print("common values =", np.intersect1d(a1,a2))

common values = [2]


#### 14. Create a random vector of size 10 and sort it (★★☆)

In [16]:
print("Sorted vector =", np.sort(np.random.randint(-10,10,(1,10)))[0])

Sorted vector = [-10 -10  -9  -7  -7  -6  -1   6   8   8]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [185]:
a   = np.random.randint(-22,22,10) # random vec
print("Original matrix ", a)
m   = np.max(a)                # max value 
idx = np.where(a==m)        # index of max (this is a bug it assumes that it only appears once!)
#print(idx)
a[idx]=0
print("Substited matrix =", a)

Original matrix  [-13  12   0  -7  19   0 -13   4  -1  -5]
Substited matrix = [-13  12   0  -7   0   0 -13   4  -1  -5]


In [183]:
a   = np.random.randint(-22,22,10)
a

array([ -3,   8, -22,  10,  -5,   0,  -3,  18,   8,  20])

In [194]:
a = np.random.random(10)
print(a,f' \n index of maximum value is {a.argmax()}')
a[a.argmax()]=0 
a

[0.61289699 0.37337994 0.98903882 0.09534677 0.66011999 0.33864683
 0.58733804 0.10527007 0.24170736 0.83075836]  
 index of maximum value is 2


array([0.61289699, 0.37337994, 0.        , 0.09534677, 0.66011999,
       0.33864683, 0.58733804, 0.10527007, 0.24170736, 0.83075836])

In [195]:
Z = np.random.random((10,10))
Z[Z.argmax(axis=0)] = 0
print(Z)

[[0.59883805 0.53038654 0.01214046 0.83476472 0.67526257 0.68482048
  0.00449204 0.6455357  0.20742867 0.04698355]
 [0.21514517 0.50470743 0.32409895 0.35038862 0.60550337 0.34811257
  0.29486102 0.30396138 0.48506106 0.08846618]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.81098162 0.27393946 0.33374191 0.89676313 0.48040269 0.55567923
  0.30532196 0.64195621 0.40957079 0.77326008]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         

#### 16. Subtract the mean of each row of a matrix (★★☆)

In [18]:
rmat = np.random.randint(-100,100,size=(4,4)) # generate a random matrix
rmat_subt_mean = rmat-np.diag(np.mean(rmat,axis=1)) # subtract the means (axis=1 gives means of the rows)
print(rmat_subt_mean)

[[-57.    80.    30.    76.  ]
 [-70.   -56.5   -3.    74.  ]
 [ 81.    17.   -89.75 -18.  ]
 [-43.    -6.    78.   -35.  ]]


#### 17. How to get the n largest values of an array (★★★)

In [19]:
v = np.random.rand(1,10) # first do it for a vector 
v = v[0]
print(v)

[0.28815033 0.43985525 0.55482623 0.06247779 0.75491715 0.10327721
 0.65993099 0.87623118 0.7295161  0.2559858 ]


In [20]:
def get_n_largest_of_vec(vec,n):
    vec.sort()
    vrev = v[::-1]
    return vrev[0:n]

In [21]:
print(get_n_largest_of_vec(v,3))

[0.87623118 0.75491715 0.7295161 ]


In [22]:
print(rmat)

[[-14  80  30  76]
 [-70 -75  -3  74]
 [ 81  17 -93 -18]
 [-43  -6  78 -37]]


In [23]:
def get_n_largest_of_mat(mat,n):
    if type(n) != int:
        return print("Error: n must be an integer")   
    elif n > mat.size:
        return print("Error: n must be less that the number of elements of the matrix")
    mf = mat.flatten() # change it to a vector
    mf.sort() # sort it from low to high
    mfrev = mf[::-1] # reverse the order 
    return mfrev[0:n] # slice the top n values and return as a vector

In [24]:
print(get_n_largest_of_mat(rmat,10))

[ 81  80  78  76  74  30  17  -3  -6 -14]


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36)

<i> Here we use the where method </i>

In [25]:
rmat35 = np.random.randint(0,10,size=(5,3))

print(rmat35)

rmat35=np.where(rmat35 > 4, rmat35 **2, rmat35)

print(rmat35)



[[8 2 2]
 [3 7 6]
 [2 1 9]
 [3 4 1]
 [8 9 4]]
[[64  2  2]
 [ 3 49 36]
 [ 2  1 81]
 [ 3  4  1]
 [64 81  4]]


### Additional questions

#### How to add a border (filled with 0's) around an existing array? (★☆☆)

In [32]:
nv = np.arange(10)
np.pad(nv,3)

array([0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0])

#### Dealing with NaNs

In [36]:
[0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
np.nan in set([np.nan]),
0.3 == 3 * 0.1]

[nan, False, False, nan, True, False]

####  Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

To Return every other element from the entire array:

In [53]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [62]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [63]:
del Z

#### Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [38]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

####  Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [70]:
print(np.dot(np.ones((5,3)),np.ones((3,2))))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [73]:
x = np.arange(10)
x[(x>3)&(x<8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### Legal operations on vectors

In [164]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
x*x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [104]:
x<<2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [105]:
x>>2

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2])

In [106]:
1j*x

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [107]:
x/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [114]:
np.array(0) / np.array(0)

/var/folders/lj/my6r3k650wl54v5nz5r6x5cm0000gn/T/ipykernel_89736/873513115.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [115]:
np.array(0) // np.array(0)

/var/folders/lj/my6r3k650wl54v5nz5r6x5cm0000gn/T/ipykernel_89736/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [116]:
np.array([np.nan]).astype(int).astype(float)

array([0.])

In [143]:
A = np.ones(3)*1
B = np.ones(3)*2
#np.add(A,B,out=B)
(A+B)*(-A/2)

array([-1.5, -1.5, -1.5])

In [140]:
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### Display four ways of getting the integer part of an array

In [163]:
Z = np.random.uniform(0,10,10)
Z//1 == (Z-Z%1)
(Z-Z%1) == np.floor(Z)
Z.astype(int) == np.floor(Z)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

array([8, 2, 2, 9, 2, 0, 0, 6, 4, 0])

#### Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [157]:
Z = np.zeros((5,5))
Z += np.arange(5)

#### Inverse of a matrix

In [210]:
Z = np.random.random((3,3))
1/Z

array([[ 2.19350266,  3.89570489, 16.96419292],
       [ 2.82207355,  1.02504115,  4.61806533],
       [44.61053515,  2.50709529,  2.21722673]])

In [198]:
Z

array([[0.7923353 , 0.80731927, 0.03965707],
       [0.59261135, 0.77983771, 0.62036145],
       [0.25964474, 0.37475783, 0.89719888]])

In [203]:
Zinv=np.linalg.inv(Z)

In [209]:
np.dot(Zinv,Z).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

#### 59. How to sort an array by the nth column? (★★☆)

In [217]:
Z = np.random.randint(0,50,size=(10,10))
Z

array([[ 5, 22, 40,  7, 27, 20,  8, 19, 24, 41],
       [10, 39, 45, 42,  4, 25, 16, 21, 13, 21],
       [18, 19,  6, 16, 12, 31, 45, 32, 47, 35],
       [14,  9,  6, 43, 19, 19,  5, 28, 14, 48],
       [12,  7, 32, 42,  3, 27, 16, 26, 32, 32],
       [38, 16, 17, 38, 46, 32, 27,  4, 49,  4],
       [13, 33, 38, 23, 34, 25, 46, 11,  3, 22],
       [35, 17,  9, 35, 28, 19, 13,  4, 18, 35],
       [35, 47, 29, 21, 17, 22,  3, 36, 36, 34],
       [14,  2, 42, 46, 44, 32, 23, 11, 23, 12]])

In [216]:
Z[Z[:,1].argsort()]

array([[ 6,  0, 24, 15, 45, 15, 31, 25, 24, 32],
       [32,  3, 37, 49, 30, 12,  9, 34, 42, 22],
       [17, 11, 20, 44, 39, 26, 30, 34,  1, 20],
       [30, 12, 20, 44, 24, 16, 47, 34, 15,  6],
       [25, 13, 24,  7,  9, 14, 47, 26, 13, 32],
       [11, 14, 33,  2, 42, 40,  4,  9, 15, 20],
       [ 2, 18, 29, 45, 23,  8, 22, 26,  6, 11],
       [45, 33,  7, 23, 46,  7, 30, 25, 32, 39],
       [ 7, 37, 22, 14, 34, 43, 15, 31, 16, 39],
       [15, 43, 34, 48, 10, 16, 41, 12,  6, 15]])

In [220]:
def arr_col_sort(arr,col):
    return arr[arr[:,col].argsort()]

In [221]:
arr_col_sort(Z,1)

array([[14,  2, 42, 46, 44, 32, 23, 11, 23, 12],
       [12,  7, 32, 42,  3, 27, 16, 26, 32, 32],
       [14,  9,  6, 43, 19, 19,  5, 28, 14, 48],
       [38, 16, 17, 38, 46, 32, 27,  4, 49,  4],
       [35, 17,  9, 35, 28, 19, 13,  4, 18, 35],
       [18, 19,  6, 16, 12, 31, 45, 32, 47, 35],
       [ 5, 22, 40,  7, 27, 20,  8, 19, 24, 41],
       [13, 33, 38, 23, 34, 25, 46, 11,  3, 22],
       [10, 39, 45, 42,  4, 25, 16, 21, 13, 21],
       [35, 47, 29, 21, 17, 22,  3, 36, 36, 34]])